name: Deploy Docker Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend
        run: docker build -t backend ./backend

      - name: Build Frontend
        run: docker build -t frontend ./frontend

      - name: Verificar Compose
        run: docker compose config